apiVersion: v1
kind: ServiceAccount
metadata:
  name: glassbox
  namespace: genai-demo
  annotations:
    iam.gke.io/gcp-service-account: glassbox-app@${PROJECT}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: glassbox-monitoring
  namespace: genai-demo
  annotations:
    iam.gke.io/gcp-service-account: glassbox-monitoring@${PROJECT}.iam.gserviceaccount.com
